# Generated by Django 5.1.3 on 2024-12-31 08:15

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owner_email', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('service_name', models.CharField(max_length=255, null=True)),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('profile_img', models.URLField(null=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterOwner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('email', models.EmailField(max_length=50, unique=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=20)),
                ('face_embedding', models.JSONField()),
                ('phone', models.CharField(max_length=20)),
                ('license_img', models.URLField()),
                ('dob', models.DateField()),
                ('hired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=255)),
                ('rating', models.IntegerField(verbose_name=range(1, 5))),
                ('comment_type', models.CharField(choices=[('Feedback', 'Feedback'), ('Report', 'Report')], max_length=10)),
                ('comment', models.TextField()),
                ('owner_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='myapi.owner')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapi.renter')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('number', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car'), ('Elite Car', 'Elite Car'), ('Pickup Truck', 'Pickup Truck')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('rate_description', models.CharField(max_length=255)),
                ('year_of_manufacture', models.DateField()),
                ('condition_description', models.CharField(max_length=255)),
                ('img', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='myapi.owner')),
            ],
        ),
    ]
