/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/api`; params?: Router.UnknownInputParams; } | { pathname: `/authenticate`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/authenticate/login`; params?: Router.UnknownInputParams; } | { pathname: `/authenticate/register`; params?: Router.UnknownInputParams; } | { pathname: `/owner/add-renter`; params?: Router.UnknownInputParams; } | { pathname: `/owner/profile`; params?: Router.UnknownInputParams; } | { pathname: `/owner/renter-feedback`; params?: Router.UnknownInputParams; } | { pathname: `/owner/renter-profile`; params?: Router.UnknownInputParams; } | { pathname: `/owner/renter-scan`; params?: Router.UnknownInputParams; } | { pathname: `/owner/vehicle-adding`; params?: Router.UnknownInputParams; } | { pathname: `/owner/vehicle-list`; params?: Router.UnknownInputParams; } | { pathname: `/owner/vehicle-status`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/api`; params?: Router.UnknownOutputParams; } | { pathname: `/authenticate`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/authenticate/login`; params?: Router.UnknownOutputParams; } | { pathname: `/authenticate/register`; params?: Router.UnknownOutputParams; } | { pathname: `/owner/add-renter`; params?: Router.UnknownOutputParams; } | { pathname: `/owner/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/owner/renter-feedback`; params?: Router.UnknownOutputParams; } | { pathname: `/owner/renter-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/owner/renter-scan`; params?: Router.UnknownOutputParams; } | { pathname: `/owner/vehicle-adding`; params?: Router.UnknownOutputParams; } | { pathname: `/owner/vehicle-list`; params?: Router.UnknownOutputParams; } | { pathname: `/owner/vehicle-status`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/api${`?${string}` | `#${string}` | ''}` | `/authenticate${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/authenticate/login${`?${string}` | `#${string}` | ''}` | `/authenticate/register${`?${string}` | `#${string}` | ''}` | `/owner/add-renter${`?${string}` | `#${string}` | ''}` | `/owner/profile${`?${string}` | `#${string}` | ''}` | `/owner/renter-feedback${`?${string}` | `#${string}` | ''}` | `/owner/renter-profile${`?${string}` | `#${string}` | ''}` | `/owner/renter-scan${`?${string}` | `#${string}` | ''}` | `/owner/vehicle-adding${`?${string}` | `#${string}` | ''}` | `/owner/vehicle-list${`?${string}` | `#${string}` | ''}` | `/owner/vehicle-status${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/api`; params?: Router.UnknownInputParams; } | { pathname: `/authenticate`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/authenticate/login`; params?: Router.UnknownInputParams; } | { pathname: `/authenticate/register`; params?: Router.UnknownInputParams; } | { pathname: `/owner/add-renter`; params?: Router.UnknownInputParams; } | { pathname: `/owner/profile`; params?: Router.UnknownInputParams; } | { pathname: `/owner/renter-feedback`; params?: Router.UnknownInputParams; } | { pathname: `/owner/renter-profile`; params?: Router.UnknownInputParams; } | { pathname: `/owner/renter-scan`; params?: Router.UnknownInputParams; } | { pathname: `/owner/vehicle-adding`; params?: Router.UnknownInputParams; } | { pathname: `/owner/vehicle-list`; params?: Router.UnknownInputParams; } | { pathname: `/owner/vehicle-status`; params?: Router.UnknownInputParams; };
    }
  }
}
